### ISSUE TITLE
[Game]リファクタリング

### ISSUE THREAD

**Issue by AuroraSloan** [katataku/ft_transcendence#121]
ファイル内容を減らし、ゲームフロントエンドの可読性を高める

- [x] split game and match
- [x] fix up game
- [x] fix up match

**Comment by AuroraSloan** [comment]
私はGameのリファクタリングにやってみて始めました。最初の目標はGameをMatchから分離することだったのだが、ちょっと行き詰ってしまった。マッチングがユーザーを認識していないようなのです。
Gameのリファクタリングを見てもらえませんか？
近い将来、コードが大きく変わるかもしれないので、もしこのGameコンポーネントが今後の変更にうまく対応できると思われるなら、ブランチを少し編集するのを手伝ってもらえませんか？しかし、もしあまりに違うようであれば、ブランチを閉じて、後でそのissueを完成させるようにしましょう :)

**Comment by shima8823** [comment]
feat/121-game-refactoring branchのことですね！diffがないので、どこを変更したのか分からないです。後でissueを完成させることにできませんか？

**Comment by AuroraSloan** [comment]
あ、すみません！リンクを貼るのを忘れていました。

https://github.com/katataku/ft_transcendence/compare/feat/82-match-list...feat/121-game-refactoring

バックエンドとフロントエンドが完全に統合されていないので、今すぐリファクタリングするのは少し難しいかもしれませんね。
