### ISSUE TITLE
[General] type定義について

### ISSUE THREAD

**Issue by tharaguc** [katataku/ft_transcendence#135]
req,resのようにback front両方で使用するような型に関しては共通のパッケージを作ってそこからimportしたほうがいいと思います。
```
.
+-- backend
+-- frontend
+-- commonTypes
    +-- index.d.ts
    +-- package.json
```

**Comment by katataku** [comment]
おおすごい！そんなことできるんですね！

2つ同じの作るの微妙だなと思ってたので、めっちゃ嬉しいです

**Comment by tharaguc** [comment]
色々やってみましたができなかったので別々に定義するしかなさそうです。nestでinterfaceではなくDtoを使っているのでfrontとの共有はできなかったです。
