### ISSUE TITLE
[BUG]ブラウザリロードすると、ログイン状態が消える

### ISSUE THREAD

**Issue by katataku** [katataku/ft_transcendence#189]
[現状の動作・問題点]
ログイン後にチャット画面などで、ブラウザリロードすると、ログイン状態が消える。
Contextに保存された情報はブラウザリロードにより初期化されるため。

[期待される動作]
以下のいづれか。
- リロードを禁止する
- リロードを許可するならば、ログイン状態は消えなくする。

[対応方針(あれば)]
チャットルーム一覧の更新などの目的で、リロードは許可したいです。
ローカルストレージに格納するとリロードしてもContextは消えなくできる？

[参考資料]
https://reffect.co.jp/react/react-usecontext-understanding#Local_Storage

**Comment by tharaguc** [comment]
ありがとうございます。JWTによる認識を実装するときにやろうと思っていたので、現状は保持されないです。最低限の実装だけしてPR出します

**Comment by katataku** [comment]
> ありがとうございます。JWTによる認識を実装するときにやろうと思っていたので、現状は保持されないです。最低限の実装だけしてPR出します

すでに検討済みだったのですね！ありがとうございます！

**Comment by katataku** [comment]
#190 で対応済みのためクローズ
