### ISSUE TITLE
[User] Password validation

### ISSUE THREAD

**Issue by tharaguc** [katataku/ft_transcendence#191]
debug時は短いほうがいいので最後のほうにやります

**Comment by katataku** [comment]
このチケットは、
パスワードの長さとか文字種別のルールを設定して、そのルールを守ってるかvalidationする。
って感じですか？

**Comment by tharaguc** [comment]
> このチケットは、
> 
> パスワードの長さとか文字種別のルールを設定して、そのルールを守ってるかvalidationする。
> 
> って感じですか？

そうです

**Comment by katataku** [comment]
備忘：#317 でパスワード修正もできるようにしたので、合わせて対応する。
