### ISSUE TITLE
ゲームのcypressテスト

### ISSUE THREAD

**Issue by AuroraSloan** [katataku/ft_transcendence#258]

**Comment by katataku** [comment]
参考です。
https://docs.cypress.io/guides/references/trade-offs#Multiple-browsers-open-at-the-same-time

まだちゃんと読めてないのですが、cypressで複数ブラウザを同時に開くことはできないみたいで、テストのために工夫が必要とのことです。

あまりテストに時間をかけなくてもいいかなと思ってます。
時間がかかるようなら、「ゲームを開始できること」までの確認とか、一つのブラウザでできる確認まででOKだと思いました。

**Comment by AuroraSloan** [comment]
おお、参考ありがとうございます！！
なるほどね、早く上手く出来るか信じがないです。
最悪の場合、マッチリストのページに移動し、ゲームのページに移動してplayボタンを押すテストくらいは出来ると思うのですが :)
