### ISSUE TITLE
[インフラ] 本番環境を想定したBuildとホスティング

### ISSUE THREAD

**Issue by tharaguc** [katataku/ft_transcendence#329]
- React
開発は`npm run start`だがレビュー用には、`npm run build`をしてserveなどの簡易的なサーバアプリケーションでホスティングする。
- Nest
開発は`npm start:dev`だがレビュー用には`nest build`をして`node dist/main.js`でホスティングする。

**Comment by katataku** [comment]
これって必須ですか？
メリットとかが理解できてなくて伺いたいです！

**Comment by tharaguc** [comment]
必須ではないですが、レビュー時に開発モードで動いていたら、自分がレビュワーなら気になるというのと、単なる学習の一部です。
