### ISSUE TITLE
[バックエンド]NestJSのディレクトリ構成について

### ISSUE THREAD

**Issue by tharaguc** [katataku/ft_transcendence#38]
hogeという機能があったら
```
hoge.entity.ts
hoge.controller.ts
hoge.module.ts
hoge.service.ts
```
という４つのファイル構成で作成をお願いします。
entity -> TypeORM経由でDBの構成を定義
controller -> ルーティングを定義
service -> ルーティング内の具体的な処理を定義
module -> 上記すべてをまとめてmainにわたす

**Comment by katataku** [comment]
documentation labelがついてるってことは、Wikiに開発ルールとして追記するイメージですか？
僕は、追記していくことに賛成です！

**Comment by katataku** [comment]
一つの大きな機能に２画面ある時ってどうするのがいいでしょうか。

例えば、Chat機能という大きな機能の中に
- chatList:チャットルームを選択するための画面
- chat:メッセージをやり取りする画面
がある場合です。

**Comment by tharaguc** [comment]
Backendなので画面単位で考えなくても大丈夫だと思います

**Comment by katataku** [comment]
> Backendなので画面単位で考えなくても大丈夫だと思います

つまり、画面単位で考えず、同じディレクトリ内に複数のファイルを置く（8個とか12個置くイメージ）であってますか？ 先ほどのチャットでのプルリクの感じで。

**Comment by tharaguc** [comment]
複雑なtable構造が出てきた時にどう対応するのかがわかってないので、ちょっとディレクトリ構成について考え直したほうが良さそうです。

**Comment by katataku** [comment]
https://github.com/CatsMiaow/nestjs-project-structure

ディレクトリ構成の参考見つけてきました。
原則Moduleごとにsrc配下にディレクトリ作るみたいです。（If it's small, you don't need to add folders.）

今回の僕たちに当てはめると、APIのエンドポイントごとにディレクトリ作った方がいいのかな？
ディレクトリめっちゃ増えそうな気はします。。。

**Comment by katataku** [comment]
一つ前のコメントを参考に、ディレクトリ構成案を作りました。
基本は、参考URLと同じですが、以下の点が、ポイントになるかなと思います。

- entity.tsは全て`src/entity`にまとめる。そのことにより、「複雑なtable構造でもとりあえず一つのディレクトリで管理できる」「UserProfileなど機能を横断するテーブルにもアクセスしやすい」などがメリットだと考えています。
- Moduleごとにsrc配下にディレクトリを作成。
    - 僕たちの例だとAPIエンドポイントごと、ということになると思います。細かいディレクトリが増えそうですが、まずはこれでやってみたいです。
    - Moduleを分割するのは大変ですが、合併するのは`*.module.ts`にControllerとかを登録すればいいだけ？と、楽観的に考えています。
- Moduleディレクトリには、index.tsを配置。呼び出す側は、このファイルをimportすればいいようにする。



```sh
+-- bin // Custom tasks
+-- dist // Source build
+-- node_modules
+-- src
|   +-- config // Environment Configuration
|   +-- entity // TypeORM Entities
|   +-- auth // Authentication
|   +-- common // Global Nest Module
|   |   +-- constants // Constant value and Enum
|   |   +-- controllers // Nest Controllers
|   |   +-- decorators // Nest Decorators
|   |   +-- dto // DTO (Data Transfer Object) Schema, Validation
|   |   +-- filters // Nest Filters
|   |   +-- guards // Nest Guards
|   |   +-- interceptors // Nest Interceptors
|   |   +-- interfaces // TypeScript Interfaces
|   |   +-- middleware // Nest Middleware
|   |   +-- pipes // Nest Pipes
|   |   +-- providers // Nest Providers
|   +-- shared // Shared Nest Modules
|   +-- healthCheck
|   |   +-- healthCheck.constant.ts
|   |   +-- healthCheck.controller.ts
|   |   +-- healthCheck.service.ts
|   |   +-- healthCheck.module.ts
|   |   +-- healthCheck.*.ts
|   |   +-- index.ts
|   |   +-- * // Other Nest Modules, non-global, same as common structure above
|   +-- chat
|   |   +-- chat.constant.ts
|   |   +-- chat.controller.ts
|   |   +-- chat.service.ts
|   |   +-- chat.module.ts
|   |   +-- chat.*.ts
|   |   +-- index.ts
|   |   +-- * // Other Nest Modules, non-global, same as common structure above
|   +-- chatMuteUser
|   |   +-- chatMuteUser.constant.ts
|   |   +-- chatMuteUser.controller.ts
|   |   +-- chatMuteUser.service.ts
|   |   +-- chatMuteUser.module.ts
|   |   +-- chatMuteUser.*.ts
|   |   +-- index.ts
|   |   +-- * // Other Nest Modules, non-global, same as common structure above
+-- test // Jest testing
+-- typings // Modules and global type definitions
```
