### ISSUE TITLE
[共通インフラ]TypeORMのmigration設定

### ISSUE THREAD

**Issue by katataku** [katataku/ft_transcendence#45]
[背景]
現在はTypeORMのsynclonze機能を使ってDBにテーブル作成を行っている。
TypeORMのmigration機能を使うことで、

- DBのテーブルの作成
- テーブルへのレコードの挿入

を行うことができる。

[対応方針]
動作確認用のサンプルデータ挿入を目的に本機能を利用する。
（詳細は要勉強・・・）

[参考URL]
https://orkhan.gitbook.io/typeorm/docs/migrations

https://medium.com/@emfelipe/using-typeorm-migrations-for-simple-database-seeding-nestjs-example-1f1acbc0ef24

**Comment by tharaguc** [comment]
#35との違いはありますか？

**Comment by tharaguc** [comment]
#35

**Comment by katataku** [comment]
#35 とかぶってますね・・！失礼しました！
まさにseeding周りの対応をしたいという意図の起票でした。
