### ISSUE TITLE
backend→DBへの接続（ヘルスチェックAPIの追加）

### ISSUE THREAD

**Issue by katataku** [katataku/ft_transcendence#7]
nestjsでpostgresへの接続を行う。
health check用の処理を用意する。

- postgres側でhealth checkテーブルを用意する。（1カラムだけ適当に項目を用意）
- nestjsからヘルスチェックテーブルの値を読み取る処理を追加
- nestjsにhealth check APIを用意。health checkを呼ばれるとhealth checkテーブルの値を返す。（読み取り処理が正常にできていることを確認するためのAPI）

### ORMについて
nestjsが推奨しているTypeORMを使用してアクセスを行う。
https://docs.nestjs.com/techniques/database

### 参考資料

- https://zenn.dev/yutaro_matsu/scraps/b7e7bfa82bd091

**Comment by tharaguc** [comment]
## 参考資料
https://qiita.com/honda28/items/1c405b45263df8131bb7
