### ISSUE TITLE
[BUG]PostgresのログにWARNINGが表示される。

### ISSUE THREAD

**Issue by katataku** [katataku/ft_transcendence#77]
[現状の動作・問題点]
`WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted`のWARNINGが表示される。

[期待される動作]
WARNINGが表示されない。

[対応方針(あれば)]
要調査

**Comment by katataku** [comment]
わかる方いれば、コメントください！

**Comment by AuroraSloan** [comment]
最近、解決されたのでしょうか？今日気づいたのですが、エラーが表示されないのですが
